version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:7.8.0
    environment:
      cluster.name: elasticsearch
      discovery.type: single-node
      bootstrap.memory_lock: 'true'
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '9200:9200'
    volumes:
      - ./esdata01:/usr/share/elasticsearch/data
    networks:
      - default

  kibana:
    image: kibana:7.8.0
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - '5601:5601'
    depends_on:
      - 'elasticsearch'
    networks:
      - default

  fpl-crawler:
    build: .
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - '8080:8080'
    depends_on:
      - 'elasticsearch'
    networks:
      - default

networks:
  default: